services:
  - type: web
    name: task-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: task-manager-db
    databaseName: taskmanager
    user: taskmanager
